"use client";
import Link from "next/link";
import {useEffect} from "react";
import {ArrowUpRight,LogOut} from "lucide-react";
import {useRouter} from "next/navigation";
import {useAuth} from "@/components/auth-provider";
import {useLocale} from "@/components/locale-provider";
import {Skeleton,ErrorState} from "@/components/ui";
export function AccountPage(){const{t}=useLocale();const{status,user,logout}=useAuth();const router=useRouter();useEffect(()=>{if(status==="unauthenticated")router.replace("/login?next=/account")},[status,router]);if(status==="unknown")return <div className="container-vanta py-16"><Skeleton className="h-12 w-1/2"/><Skeleton className="mt-8 h-44"/></div>;if(status==="unauthenticated")return null;if(!user)return <div className="container-vanta py-16"><ErrorState message="Session data is unavailable."/></div>;return <div className="page-shell"><div className="container-vanta py-12 sm:py-16"><span className="text-xs uppercase tracking-[.2em] text-[var(--muted)]">{t("account.title")}</span><h1 className="mt-3 text-4xl font-semibold sm:text-6xl">{t("account.welcome")}, {user.name}</h1><div className="mt-10 grid gap-4 md:grid-cols-3"><div className="card p-6"><small className="text-[var(--muted)]">{t("auth.email")}</small><p className="mt-2 break-all font-medium">{user.email}</p></div><div className="card p-6"><small className="text-[var(--muted)]">{t("auth.phone")}</small><p className="mt-2 font-medium">{user.phone||"—"}</p></div><div className="card p-6"><small className="text-[var(--muted)]">Role</small><p className="mt-2 font-medium">{user.role||"user"}</p></div></div><div className="mt-8 grid gap-3 sm:grid-cols-2"><Link href="/orders" className="card flex items-center justify-between p-5"><span>{t("account.orders")}</span><ArrowUpRight size={18}/></Link><Link href="/cart" className="card flex items-center justify-between p-5"><span>{t("account.cart")}</span><ArrowUpRight size={18}/></Link></div><button className="mt-8 inline-flex min-h-11 items-center gap-2 border border-[var(--border)] px-5 text-sm font-semibold" onClick={async()=>{await logout();router.replace("/")}}><LogOut size={17}/>{t("account.logout")}</button></div></div>}
