"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {usePathname,useRouter} from "next/navigation";
import {BarChart3,Boxes,ClipboardList,Tags,Users,ShieldAlert} from "lucide-react";
import {useAuth} from "@/components/auth-provider";
import {useLocale} from "@/components/locale-provider";
import {adminService,unwrapOrders} from "@/services/admin";
import {Skeleton} from "@/components/ui";
export function AdminShell({children}:{children:React.ReactNode}){const{t}=useLocale();const{status,role}=useAuth();const[path,setPath]=useState("");const pathname=usePathname();const router=useRouter();const[verified,setVerified]=useState(false);const[denied,setDenied]=useState(false);useEffect(()=>{setPath(pathname)},[pathname]);useEffect(()=>{if(status!=="authenticated")return;if(role==="admin"){setVerified(true);return}adminService.orders().then(payload=>{unwrapOrders(payload);sessionStorage.setItem("vanta-session",JSON.stringify({role:"admin"}));setVerified(true)}).catch(()=>setDenied(true))},[status,role]);useEffect(()=>{if(status==="unauthenticated")router.replace("/login?next=/admin")},[status,router]);if(status==="unknown"||status==="authenticated"&&!verified&&!denied)return <div className="container-vanta py-12"><Skeleton className="h-12 w-1/3"/><Skeleton className="mt-8 h-96"/></div>;if(denied||status!=="authenticated")return <div className="container-vanta grid min-h-[60vh] place-items-center py-16"><div className="card max-w-lg p-8 text-center"><ShieldAlert className="mx-auto"/><h1 className="mt-4 text-2xl font-semibold">{t("admin.denied")}</h1></div></div>;const nav=[["/admin",t("admin.overview"),BarChart3],["/admin/products",t("admin.products"),Boxes],["/admin/orders",t("admin.orders"),ClipboardList],["/admin/users",t("admin.users"),Users],["/admin/categories",t("admin.categories"),Tags]] as const;return <div className="page-shell"><div className="container-vanta py-8"><div className="grid gap-8 lg:grid-cols-[220px_1fr]"><aside className="card h-fit p-3 lg:sticky lg:top-28"><nav className="grid gap-1">{nav.map(([href,label,Icon])=><Link key={href} href={href} className={"flex items-center gap-3 px-4 py-3 text-sm "+(path===href?"bg-[var(--primary)] text-[var(--primary-fg)]":"hover:bg-[var(--surface-2)]")}><Icon size={17}/>{label}</Link>)}</nav></aside><section className="min-w-0">{children}</section></div></div></div>}
