"use client";
import Link from "next/link";
import {Eye,EyeOff,ArrowRight} from "lucide-react";
import {useEffect,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import {useAuth} from "@/components/auth-provider";
import {useLocale} from "@/components/locale-provider";
import {authService} from "@/services/auth";
import {Button} from "@/components/ui";
function Field({label,type="text",value,onChange,autoComplete}:{label:string;type?:string;value:string;onChange:(v:string)=>void;autoComplete?:string}){return <label className="grid gap-2 text-sm font-medium"><span>{label}</span><input className="control w-full" type={type} value={value} autoComplete={autoComplete} onChange={e=>onChange(e.target.value)} required/></label>}
function Password({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){const[show,setShow]=useState(false);return <label className="grid gap-2 text-sm font-medium"><span>{label}</span><span className="relative"><input className="control w-full pe-12" type={show?"text":"password"} value={value} onChange={e=>onChange(e.target.value)} autoComplete="current-password" minLength={6} required/><button type="button" className="absolute inset-y-0 end-0 grid w-12 place-items-center" onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label>}
function Frame({title,children}:{title:string;children:React.ReactNode}){return <div className="page-shell grid place-items-center px-4 py-12 sm:px-6"><div className="grid w-full max-w-5xl overflow-hidden border border-[var(--border)] bg-[var(--surface)] lg:grid-cols-2"><div className="hidden min-h-[600px] bg-[var(--fg)] p-12 text-[var(--bg)] lg:flex lg:flex-col lg:justify-end"><span className="text-xs tracking-[.25em]">VANTA</span><p className="mt-4 max-w-md text-5xl font-semibold leading-[.95]">Clothing, without the noise.</p></div><div className="p-6 sm:p-10 lg:p-14"><span className="text-xs uppercase tracking-[.2em] text-[var(--muted)]">VANTA / ACCOUNT</span><h1 className="mt-3 text-4xl font-semibold">{title}</h1>{children}</div></div></div>}
export function LoginForm(){const{t}=useLocale();const{status,login}=useAuth();const router=useRouter();const params=useSearchParams();const next=params.get("next")||"/";const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);useEffect(()=>{if(status==="authenticated")router.replace(next)},[status,next,router]);const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await login({email,password});router.replace(next)}catch(err){setError(err instanceof Error?err.message:t("auth.invalid"))}finally{setBusy(false)}};return <Frame title={t("auth.login")}><form className="mt-8 grid gap-5" onSubmit={submit}><Field label={t("auth.email")} type="email" value={email} onChange={setEmail} autoComplete="email"/><Password label={t("auth.password")} value={password} onChange={setPassword}/>{error&&<p className="text-sm text-[var(--danger)]" role="alert">{error}</p>}<Button disabled={busy}>{busy?t("auth.working"):t("auth.login")}<ArrowRight size={16}/></Button><p className="text-sm text-[var(--muted)]">{t("auth.newAccount")} <Link href="/signup" className="font-semibold text-[var(--fg)] underline">{t("auth.signup")}</Link></p></form></Frame>}
export function SignupForm(){const{t}=useLocale();const{status}=useAuth();const router=useRouter();const[name,setName]=useState("");const[email,setEmail]=useState("");const[phone,setPhone]=useState("");const[password,setPassword]=useState("");const[otp,setOtp]=useState("");const[sent,setSent]=useState(false);const[busy,setBusy]=useState(false);const[otpBusy,setOtpBusy]=useState(false);const[error,setError]=useState("");useEffect(()=>{if(status==="authenticated")router.replace("/")},[status,router]);const send=async()=>{if(!email||!phone){setError(t("auth.invalid"));return}setOtpBusy(true);setError("");try{await authService.sendOtp({email,phone});setSent(true)}catch(e){setError(e instanceof Error?e.message:t("auth.invalid"))}finally{setOtpBusy(false)}};const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!sent){await send();return}setBusy(true);setError("");try{await authService.signup({name,email,phone,password,otp});router.replace("/login")}catch(e){setError(e instanceof Error?e.message:t("auth.invalid"))}finally{setBusy(false)}};return <Frame title={t("auth.signup")}><form className="mt-8 grid gap-5" onSubmit={submit}><Field label={t("auth.name")} value={name} onChange={setName} autoComplete="name"/><Field label={t("auth.email")} type="email" value={email} onChange={setEmail} autoComplete="email"/><Field label={t("auth.phone")} type="tel" value={phone} onChange={setPhone} autoComplete="tel"/><Password label={t("auth.password")} value={password} onChange={setPassword}/>{sent&&<Field label={t("auth.otp")} value={otp} onChange={setOtp}/>} {error&&<p className="text-sm text-[var(--danger)]" role="alert">{error}</p>}<div className="grid gap-2 sm:grid-cols-[1fr_auto]"><Button disabled={busy||sent&&otp.length!==6}>{busy?t("auth.working"):sent?t("auth.signup"):t("auth.sendOtp")}</Button>{sent&&<Button type="button" variant="secondary" disabled={otpBusy} onClick={send}>{otpBusy?t("common.loading"):t("auth.sendOtp")}</Button>}</div><p className="text-sm text-[var(--muted)]">{t("auth.existing")} <Link href="/login" className="font-semibold text-[var(--fg)] underline">{t("auth.login")}</Link></p></form></Frame>}
