"use client";
import Link from "next/link";
import {AnimatePresence,motion} from "motion/react";
import {X,Sun,Moon} from "lucide-react";
import {useEffect} from "react";
import {useLocale} from "@/components/locale-provider";
import {useTheme} from "@/components/theme-provider";
import {useAuth} from "@/components/auth-provider";
export function MobileNav({open,onClose}:{open:boolean;onClose:()=>void}){const{t,locale,switchLocale}=useLocale();const{theme,toggle}=useTheme();const{status,role}=useAuth();useEffect(()=>{if(!open)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=old}},[open]);const links:Array<[string,string]>=[["/",t("nav.home")],["/shop",t("nav.shop")],...(status==="authenticated"?[[ "/orders",t("nav.orders")],[ "/account",t("nav.account")]]:[[ "/login",t("auth.login")]]),...(role==="admin"?[[ "/admin",t("nav.admin")]]:[])];return <AnimatePresence>{open&&<><motion.button className="fixed inset-0 z-[60] bg-black/45 md:hidden" aria-label={t("common.close")} onClick={onClose} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside role="dialog" aria-modal="true" className="fixed inset-y-0 end-0 z-[70] flex w-[min(88vw,390px)] flex-col bg-[var(--bg)] p-6 md:hidden" initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}} transition={{type:"spring",stiffness:360,damping:38}}><div className="flex items-center justify-between"><b className="tracking-[.28em]">VANTA</b><button className="icon-btn" onClick={onClose} aria-label={t("common.close")}><X/></button></div><nav className="mt-12 grid gap-2">{links.map(([href,label])=><Link key={href} href={href} onClick={onClose} className="border-b border-[var(--border)] py-4 text-2xl font-medium">{label}</Link>)}</nav><div className="mt-auto grid grid-cols-2 gap-2 border-t border-[var(--border)] pt-5"><button className="control" onClick={()=>toggle()}>{theme==="dark"?<Sun size={17}/>:<Moon size={17}/>} {theme==="dark"?"Light":"Dark"}</button><button className="control" onClick={(e)=>{const r=e.currentTarget.getBoundingClientRect();switchLocale(locale==="en"?"ar":"en",{x:(r.left+r.width/2)/innerWidth*100,y:(r.top+r.height/2)/innerHeight*100});onClose()}}>{locale==="en"?"العربية":"English"}</button></div></motion.aside></>}</AnimatePresence>}
