"use client";
import Image from "next/image";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {useAuth} from "@/components/auth-provider";
import {useLocale} from "@/components/locale-provider";
import {orderService} from "@/services/orders";
import type {Order} from "@/types";
import {ErrorState,EmptyState,Skeleton} from "@/components/ui";
import {formatPrice,splitCsv} from "@/lib/utils";
export function OrdersPage(){const{t}=useLocale();const{status}=useAuth();const router=useRouter();const[orders,setOrders]=useState<Order[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=async()=>{setLoading(true);setError("");try{setOrders(await orderService.listMine())}catch(e){setError(e instanceof Error?e.message:"REQUEST_FAILED")}finally{setLoading(false)}};useEffect(()=>{if(status==="unauthenticated"){router.replace("/login?next=/orders");return}if(status==="authenticated")void load()},[status,router]);if(status==="unknown")return <div className="container-vanta py-16"><Skeleton className="h-12 w-1/3"/><Skeleton className="mt-8 h-48"/></div>;if(status==="unauthenticated")return null;return <div className="page-shell"><div className="container-vanta py-12 sm:py-16"><h1 className="text-4xl font-semibold sm:text-6xl">{t("orders.title")}</h1>{loading?<div className="mt-8 grid gap-4">{[1,2,3].map(i=><Skeleton key={i} className="h-44"/>)}</div>:error?<div className="mt-8"><ErrorState message={error} retry={load}/></div>:orders.length===0?<div className="mt-8"><EmptyState message={t("orders.empty")}/></div>:<div className="mt-8 grid gap-5">{orders.map(o=><article key={String(o.id)} className="card p-5 sm:p-7"><div className="flex flex-col gap-3 border-b border-[var(--border)] pb-4 sm:flex-row sm:justify-between"><div><small className="text-[var(--muted)]">{t("orders.order")} #{o.id}</small><p className="mt-1 text-xs text-[var(--muted)]">{o.created_at?new Date(o.created_at).toLocaleString(): "—"}</p></div><div><small className="text-[var(--muted)]">{t("orders.status")}</small><p className="font-semibold">{o.status}</p></div></div><div className="grid gap-3 pt-4">{(o.items||[]).map((item,i)=><div key={String(o.id)+"-"+item.product_id+"-"+i} className="flex items-center gap-4"><div className="relative size-14 overflow-hidden bg-[var(--surface-2)]">{splitCsv(item.image_url)[0]&&<Image src={splitCsv(item.image_url)[0]} alt="" fill sizes="56px" className="object-cover"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.title||"Product #"+item.product_id}</p><p className="text-xs text-[var(--muted)]">× {item.quantity}</p></div><b>{formatPrice(Number(item.price)*Number(item.quantity))}</b></div>)}</div><div className="mt-5 border-t border-[var(--border)] pt-4 text-end text-sm">{t("orders.total")}: <b>{formatPrice(o.total)}</b></div></article>)}</div>}</div></div>}
