"use client";
import {useEffect,useRef,useState} from "react";
import {AnimatePresence,motion} from "motion/react";
import {Search,X} from "lucide-react";
import {useRouter} from "next/navigation";
import {useLocale} from "@/components/locale-provider";
import {productService} from "@/services/products";
import type {Product} from "@/types";
export function SearchOverlay({open,onClose}:{open:boolean;onClose:()=>void}){const{t}=useLocale();const router=useRouter();const ref=useRef<HTMLInputElement>(null);const[q,setQ]=useState("");const[results,setResults]=useState<Product[]>([]);const[busy,setBusy]=useState(false);useEffect(()=>{if(!open)return;ref.current?.focus();const fn=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();addEventListener("keydown",fn);return()=>removeEventListener("keydown",fn)},[open,onClose]);useEffect(()=>{if(!open||!q.trim()){setResults([]);return}const timer=setTimeout(async()=>{setBusy(true);try{const p=await productService.byName(q.trim());setResults(p?[p]:[])}catch{setResults([])}finally{setBusy(false)}},280);return()=>clearTimeout(timer)},[open,q]);return <AnimatePresence>{open&&<motion.div role="dialog" aria-modal="true" className="fixed inset-0 z-[90] bg-[var(--bg)]" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="container-vanta pt-8 sm:pt-12"><div className="flex items-center gap-3 border-b-2 border-[var(--fg)] pb-4"><Search size={23}/><input ref={ref} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(onClose(),router.push("/shop?q="+encodeURIComponent(q)))} className="min-w-0 flex-1 bg-transparent text-2xl outline-none sm:text-4xl" placeholder={t("shop.search")} aria-label={t("shop.search")}/><button className="icon-btn" onClick={onClose} aria-label={t("common.close")}><X/></button></div><div className="py-8">{busy?<p className="text-sm text-[var(--muted)]">{t("common.loading")}…</p>:results.length? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{results.map(p=><button key={p.id} className="card p-5 text-start" onClick={()=>{onClose();router.push("/product/"+p.id)}}><b>{p.title}</b><span className="mt-1 block text-xs text-[var(--muted)]">{p.category_name}</span></button>)}</div>:q?<p className="text-sm text-[var(--muted)]">{t("shop.noResults")}</p>:<p className="text-sm text-[var(--muted)]">Type a product name and press Enter.</p>}</div></div></motion.div>}</AnimatePresence>}
