"use client";
import {useEffect,useMemo,useState} from "react";
import {SlidersHorizontal,X} from "lucide-react";
import {useSearchParams,useRouter} from "next/navigation";
import {useLocale} from "@/components/locale-provider";
import {productService} from "@/services/products";
import type {Product} from "@/types";
import {discountedPrice,splitCsv} from "@/lib/utils";
import {ProductCard} from "@/components/product-card";
import {Button,ErrorState,Skeleton} from "@/components/ui";
type Sort="newest"|"price-low"|"price-high";
export function ShopPage(){const{t}=useLocale();const params=useSearchParams();const router=useRouter();const[products,setProducts]=useState<Product[]>([]);const[q,setQ]=useState(params.get("q")||"");const[cat,setCat]=useState(params.get("category")||"all");const[size,setSize]=useState(params.get("size")||"all");const[color,setColor]=useState(params.get("color")||"all");const[sort,setSort]=useState<Sort>((params.get("sort") as Sort)||"newest");const[min,setMin]=useState(Number(params.get("min")||0));const[max,setMax]=useState(Number(params.get("max")||100000));const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[filtersOpen,setFiltersOpen]=useState(false);
 useEffect(()=>{let active=true;productService.all().then(d=>active&&setProducts(d)).catch(e=>active&&setError(e instanceof Error?e.message:"REQUEST_FAILED")).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 useEffect(()=>{const p=new URLSearchParams();if(q)p.set("q",q);if(cat!=="all")p.set("category",cat);if(size!=="all")p.set("size",size);if(color!=="all")p.set("color",color);if(sort!=="newest")p.set("sort",sort);if(min>0)p.set("min",String(min));if(max<100000)p.set("max",String(max));router.replace(p.toString()?"/shop?"+p.toString():"/shop",{scroll:false})},[q,cat,size,color,sort,min,max,router]);
 const cats=useMemo(()=>[...new Set(products.map(p=>p.category_name).filter(Boolean))], [products]);const sizes=useMemo(()=>[...new Set(products.flatMap(p=>splitCsv(p.sizes)))],[products]);const colors=useMemo(()=>[...new Set(products.flatMap(p=>splitCsv(p.colors)))],[products]);
 const visible=useMemo(()=>{const nq=q.trim().toLowerCase();return products.filter(p=>(!nq||p.title.toLowerCase().includes(nq)||String(p.description||"").toLowerCase().includes(nq))&&(cat==="all"||p.category_name===cat)&&(size==="all"||splitCsv(p.sizes).includes(size))&&(color==="all"||splitCsv(p.colors).includes(color))&&discountedPrice(p)>=min&&discountedPrice(p)<=max).sort((a,b)=>sort==="price-low"?discountedPrice(a)-discountedPrice(b):sort==="price-high"?discountedPrice(b)-discountedPrice(a):b.id-a.id)},[products,q,cat,size,color,sort,min,max]);
 const clear=()=>{setQ("");setCat("all");setSize("all");setColor("all");setSort("newest");setMin(0);setMax(100000)};
 const Filters=()=> <div className="grid gap-4 lg:grid-cols-6"><label className="grid gap-2 text-xs"><span>{t("shop.category")}</span><select className="control" value={cat} onChange={e=>setCat(e.target.value)}><option value="all">{t("shop.all")}</option>{cats.map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-xs"><span>{t("shop.size")}</span><select className="control" value={size} onChange={e=>setSize(e.target.value)}><option value="all">{t("shop.all")}</option>{sizes.map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-xs"><span>{t("shop.color")}</span><select className="control" value={color} onChange={e=>setColor(e.target.value)}><option value="all">{t("shop.all")}</option>{colors.map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-xs"><span>Min</span><input className="control" type="number" min="0" value={min} onChange={e=>setMin(Number(e.target.value)||0)}/></label><label className="grid gap-2 text-xs"><span>Max</span><input className="control" type="number" min="0" value={max} onChange={e=>setMax(Number(e.target.value)||100000)}/></label><button className="min-h-11 border border-[var(--border)] px-4 text-xs font-semibold hover:bg-[var(--surface-2)]" onClick={clear}>{t("shop.clear")}</button></div>;
 return <div className="page-shell"><div className="container-vanta py-10 sm:py-14"><div className="flex flex-col gap-5 border-b border-[var(--border)] pb-8 lg:flex-row lg:items-end lg:justify-between"><div><span className="text-xs uppercase tracking-[.2em] text-[var(--muted)]">VANTA</span><h1 className="mt-3 text-4xl font-semibold sm:text-6xl">{t("shop.title")}</h1><p className="mt-3 text-sm text-[var(--muted)]">{t("shop.subtitle")}</p></div><div className="flex gap-2"><input className="control hidden w-64 md:block" value={q} onChange={e=>setQ(e.target.value)} placeholder={t("shop.search")} aria-label={t("shop.search")}/><Button variant="ghost" onClick={()=>setFiltersOpen(true)}><SlidersHorizontal size={16}/>{t("shop.category")}</Button></div></div>{error?<div className="py-14"><ErrorState message={error}/></div>:loading?<div className="grid grid-cols-2 gap-x-4 gap-y-12 pt-10 md:grid-cols-3 lg:grid-cols-4">{Array.from({length:8},(_,i)=><Skeleton key={i} className="aspect-[3/4]"/>)}</div>:<><div className="flex items-center justify-between py-6 text-xs text-[var(--muted)]"><span>{visible.length} {t("shop.count")}</span><select className="control" value={sort} onChange={e=>setSort(e.target.value as Sort)} aria-label={t("shop.sort")}><option value="newest">{t("shop.newest")}</option><option value="price-low">{t("shop.priceLow")}</option><option value="price-high">{t("shop.priceHigh")}</option></select></div><div className="grid grid-cols-2 gap-x-4 gap-y-12 md:grid-cols-3 lg:grid-cols-4 lg:gap-x-6">{visible.map(p=><ProductCard key={p.id} product={p}/>)}</div>{visible.length===0&&<div className="py-16 text-center text-sm text-[var(--muted)]">{t("shop.noResults")}</div>}<div className="mt-14 hidden border-t border-[var(--border)] pt-8 lg:block"><Filters/></div></>}</div><div className="fixed inset-0 z-[100] pointer-events-none lg:hidden">{filtersOpen&&<div className="pointer-events-auto absolute inset-0 flex items-end bg-black/45" onClick={()=>setFiltersOpen(false)}><aside role="dialog" aria-modal="true" className="w-full bg-[var(--bg)] p-5" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="font-semibold">{t("shop.category")}</h2><button className="icon-btn" onClick={()=>setFiltersOpen(false)} aria-label={t("common.close")}><X/></button></div><div className="pt-4"><Filters/></div></aside></div>}</div></div>}
