"use client";import {AlertCircle,ChevronDown,LoaderCircle,X} from "lucide-react";import {AnimatePresence,motion} from "motion/react";import {useEffect,useRef} from "react";import {cn,statusTone} from "../lib/utils";
export function Button({children,className,variant="solid",loading=false,...p}:{children:React.ReactNode;className?:string;variant?:"solid"|"outline"|"ghost"|"danger";loading?:boolean}&React.ButtonHTMLAttributes<HTMLButtonElement>){return <button {...p} disabled={loading||p.disabled} className={cn("btn","btn-"+variant,className)}>{loading?<LoaderCircle className="icon spin"/>:null}{children}</button>}
export function Field({label,error,...p}:{label:string;error?:string}&React.InputHTMLAttributes<HTMLInputElement>){const id=p.id||p.name;return <label className="field" htmlFor={id}><span className="field-label">{label}</span><input {...p} id={id} className="input" aria-invalid={!!error}/>{error?<span className="field-error">{error}</span>:null}</label>}
export function Textarea({label,error,...p}:{label:string;error?:string}&React.TextareaHTMLAttributes<HTMLTextAreaElement>){const id=p.id||p.name;return <label className="field" htmlFor={id}><span className="field-label">{label}</span><textarea {...p} id={id} className="input textarea" aria-invalid={!!error}/>{error?<span className="field-error">{error}</span>:null}</label>}
export function SelectField({label,options,...p}:{label:string;options:Array<{value:string;label:string}>}&React.SelectHTMLAttributes<HTMLSelectElement>){const id=p.id||p.name;return <label className="field" htmlFor={id}><span className="field-label">{label}</span><span className="select-wrap"><select {...p} id={id} className="input select">{options.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select><ChevronDown className="select-icon"/></span></label>}
export const Skeleton=({className=""}:{className?:string})=><div className={"skeleton "+className} aria-hidden="true"/>;
export const LoadingState=({label="Loading…"}:{label?:string})=><div className="state-block" role="status"><LoaderCircle className="icon xl spin"/><p>{label}</p></div>;
export const ErrorState=({message,onRetry}:{message:string;onRetry?:()=>void})=><div className="state-block state-error" role="alert"><AlertCircle className="icon xl"/><p>{message}</p>{onRetry?<Button variant="outline" onClick={onRetry}>Try again</Button>:null}</div>;
export const EmptyState=({title,body,action}:{title:string;body?:string;action?:React.ReactNode})=><div className="state-block"><div className="empty-mark"/><h3>{title}</h3>{body?<p>{body}</p>:null}{action}</div>;
export function Price({value,oldValue,discount}:{value:number|string;oldValue?:number|string;discount?:number|string}){return <span className="price-line"><strong>EGP {Number(value).toLocaleString()}</strong>{oldValue&&Number(oldValue)!==Number(value)?<span className="price-old">EGP {Number(oldValue).toLocaleString()}</span>:null}{Number(discount)>0?<span className="discount">-{Number(discount)}%</span>:null}</span>}
export const StatusBadge=({status}:{status?:string})=><span className={"status status-"+statusTone(status)}>{status||"pending"}</span>;
export function SectionTitle({eyebrow,title,body,action}:{eyebrow?:string;title:string;body?:string;action?:React.ReactNode}){return <div className="section-heading"><div>{eyebrow?<span className="eyebrow">{eyebrow}</span>:null}<h2>{title}</h2>{body?<p>{body}</p>:null}</div>{action}</div>}
export function Modal({open,onClose,title,children,wide=false}:{open:boolean;onClose:()=>void;title:string;children:React.ReactNode;wide?:boolean}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!open)return;const prev=document.activeElement as HTMLElement|null;const h=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();addEventListener("keydown",h);document.body.style.overflow="hidden";setTimeout(()=>ref.current?.focus(),0);return()=>{removeEventListener("keydown",h);document.body.style.overflow="";prev?.focus()}},[open,onClose]);return <AnimatePresence>{open?<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" className={"modal "+(wide?"modal-wide":"")} initial={{y:16,opacity:0}} animate={{y:0,opacity:1}} exit={{y:10,opacity:0}}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Close"><X className="icon"/></button></div>{children}</motion.div></motion.div>:null}</AnimatePresence>}
