"use client";

import Link from "next/link";
import { useState } from "react";
import { CheckCircle2, CreditCard, Upload } from "lucide-react";
import { apiRequest } from "@/lib/api";
import { useAuth } from "@/stores/auth-store";
import { useCart } from "@/stores/cart-store";
import { useLang } from "@/components/transitions/language-provider";
import { PAYMENT_METHODS } from "@/lib/constants";
import { formatPrice } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { ErrorBlock, LoadingBlock } from "@/components/ui/feedback";
import { Input } from "@/components/ui/input";

export function CheckoutClient(){
  const auth=useAuth();const cart=useCart();const {t}=useLang();const [address,setAddress]=useState("");const [method,setMethod]=useState<typeof PAYMENT_METHODS[number]>("vodafone_cash");const [file,setFile]=useState<File|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState<string|null>(null);
  const valid=auth.status==="authenticated"&&cart.items.length>0&&!cart.items.some(i=>!i.available)&&address.trim().length>=10&&!!file&&!loading;
  if(auth.status==="unknown"||auth.status==="checking"||cart.status==="loading")return <main className="site-container py-12"><LoadingBlock label={t("common.loading")}/></main>;
  if(auth.status!=="authenticated")return <main className="site-container py-20 text-center"><h1 className="text-4xl font-semibold">{t("checkout.title")}</h1><p className="mt-4 text-muted-foreground">{t("cart.signin")}</p><Link href="/login" className="mt-7 inline-flex min-h-11 rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground">{t("nav.login")}</Link></main>;
  if(success)return <main className="site-container flex min-h-[65vh] items-center justify-center py-16"><div className="surface-card max-w-xl p-8 text-center md:p-12"><CheckCircle2 className="mx-auto size-10 text-success" aria-hidden/><h1 className="mt-5 text-3xl font-semibold">{t("checkout.success")}</h1><p className="mt-3 text-muted-foreground">{t("checkout.orderId")}: <span className="font-semibold text-foreground">{success}</span></p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/orders" className="inline-flex min-h-11 items-center rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground">{t("nav.orders")}</Link><Link href="/shop" className="inline-flex min-h-11 items-center rounded-full bg-secondary px-5 text-sm font-semibold text-secondary-foreground">{t("home.shop")}</Link></div></div></main>;
  const submit=async()=>{if(!valid){setError(address.trim().length<10?t("checkout.addressHint"):!file?t("checkout.screenshotHint"):t("common.required"));return;}try{setLoading(true);setError("");const form=new FormData();form.append("payment_method",method);form.append("address",address.trim());form.append("payment_screenshot",file);const response=await apiRequest<{order_id:number|string}>("/orders/confirm",{method:"POST",formData:form});setSuccess(String(response.order_id));cart.clear();}catch(err){setError(err instanceof Error?err.message:t("common.error"))}finally{setLoading(false)}};
  return <main className="site-container py-12 md:py-16"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.25em] text-muted-foreground">VANTA / CHECKOUT</p><h1 className="mt-3 text-4xl font-semibold tracking-tight md:text-6xl">{t("checkout.title")}</h1></div>{error&&<div className="mt-7"><ErrorBlock message={error}/></div>}<div className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="grid gap-5"><div className="surface-card p-6"><h2 className="text-lg font-semibold">{t("checkout.address")}</h2><p className="mt-2 text-xs text-muted-foreground">{t("checkout.addressHint")}</p><textarea value={address} onChange={(e)=>setAddress(e.target.value)} rows={5} className="mt-4 w-full resize-y rounded-2xl border border-border bg-background p-4 text-sm outline-none focus:border-ring" maxLength={300}/></div><div className="surface-card p-6"><h2 className="text-lg font-semibold">{t("checkout.payment")}</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{PAYMENT_METHODS.map((item)=><button type="button" key={item} onClick={()=>setMethod(item)} className={"flex min-h-14 items-center gap-3 rounded-2xl border px-4 text-sm font-semibold " + (method===item?"border-foreground bg-muted":"border-border")}><CreditCard className="size-4" aria-hidden/>{item==="vodafone_cash"?t("checkout.vodafone"):t("checkout.instapay")}</button>)}</div><div className="mt-5 rounded-2xl bg-muted p-4 text-xs leading-6 text-muted-foreground">{t("checkout.notice")}</div><label className="mt-5 flex min-h-32 cursor-pointer flex-col items-center justify-center gap-2 rounded-2xl border border-dashed border-border bg-background text-center"><Upload className="size-5" aria-hidden/><span className="text-sm font-semibold">{file?file.name:t("checkout.screenshot")}</span><span className="text-xs text-muted-foreground">{t("checkout.screenshotHint")}</span><Input className="hidden" type="file" accept="image/*" onChange={(e)=>setFile(e.target.files?.[0]??null)}/></label></div></section><aside className="surface-card h-fit p-6 lg:sticky lg:top-28"><h2 className="text-lg font-semibold">{t("cart.subtotal")}</h2><div className="mt-6 flex items-center justify-between text-sm"><span>{cart.items.length} {t("orders.items")}</span><span className="text-lg font-semibold">{formatPrice(cart.total)}</span></div><Button disabled={!valid} onClick={()=>void submit()} className="mt-6 w-full">{loading?t("checkout.processing"):t("checkout.place")}</Button><p className="mt-4 text-xs leading-6 text-muted-foreground">{t("checkout.backendTotal")}</p></aside></div></main>;
}
