export type Locale = "en" | "ar";

export const DICTIONARY: Record<Locale, Record<string, string>> = {
  en: {
    "nav.home": "Home", "nav.shop": "Shop", "nav.orders": "Orders", "nav.admin": "Admin", "nav.search": "Search", "nav.theme": "Theme", "nav.language": "Language", "nav.cart": "Cart", "nav.account": "Account", "nav.login": "Log in", "nav.openMenu": "Open menu", "nav.mobile": "Mobile navigation", "nav.primary": "Primary navigation",
    "home.eyebrow": "VANTA / AUTUMN EDIT", "home.title": "Quiet confidence. Built to be worn.", "home.description": "A considered wardrobe of modern essentials — clean silhouettes, tactile texture, and pieces made to live in.", "home.shop": "Shop the edit", "home.discover": "Explore collection", "home.categories": "Shop by category", "home.featured": "Featured pieces", "home.editorial": "The everyday uniform", "home.editorialBody": "Good clothes should disappear into your day while making the whole look feel intentional.", "home.viewAll": "View all", "home.values": "Less noise. Better pieces.", "home.valuesBody": "VANTA keeps the visual language simple and the product experience precise.", "home.cta": "Build your rotation",
    "shop.title": "The collection", "shop.description": "Explore current VANTA pieces and refine the edit to what fits your style.", "shop.search": "Search by product title", "shop.category": "Category", "shop.color": "Color", "shop.size": "Size", "shop.minPrice": "Min price", "shop.maxPrice": "Max price", "shop.sort": "Sort", "shop.newest": "Newest", "shop.priceLow": "Price: low to high", "shop.priceHigh": "Price: high to low", "shop.clear": "Clear filters", "shop.results": "results", "shop.empty": "No pieces match those filters.", "shop.filters": "Filters",
    "product.size": "Size", "product.color": "Color", "product.quantity": "Quantity", "product.add": "Add to cart", "product.selectSize": "Select a size", "product.selectColor": "Select a color", "product.out": "Out of stock", "product.lowStock": "Low stock", "product.description": "Description", "product.shipping": "Delivery details", "product.shippingBody": "Delivery is handled by the store. Final order cost shown here comes directly from the backend.", "product.related": "You may also like", "product.back": "Back to shop",
    "auth.login": "Log in", "auth.signup": "Create account", "auth.email": "Email", "auth.password": "Password", "auth.name": "Full name", "auth.phone": "Phone number", "auth.otp": "Verification code", "auth.sendOtp": "Send verification code", "auth.otpSent": "Code sent. Check your email.", "auth.noAccount": "New to VANTA?", "auth.haveAccount": "Already have an account?", "auth.create": "Create account", "auth.signing": "Working…", "auth.passwordHint": "At least 6 characters", "auth.otpHint": "6 digits", "auth.loginSuccess": "Welcome back.", "auth.signupSuccess": "Account created. You can log in now.",
    "account.title": "Your account", "account.profile": "Profile", "account.name": "Name", "account.email": "Email", "account.phone": "Phone", "account.orders": "Your orders", "account.cart": "Your cart", "account.logout": "Log out", "account.loggedOut": "You are not signed in.", "account.login": "Go to login",
    "orders.title": "Your orders", "orders.empty": "No orders yet.", "orders.order": "Order", "orders.status": "Status", "orders.total": "Total", "orders.date": "Date", "orders.items": "items", "orders.view": "View items", "orders.unauthorized": "Sign in to see your orders.",
    "cart.title": "Your cart", "cart.empty": "Your cart is empty.", "cart.browse": "Browse the collection", "cart.subtotal": "Subtotal", "cart.checkout": "Continue to checkout", "cart.remove": "Remove", "cart.unavailable": "Unavailable", "cart.refresh": "Refresh cart", "cart.signin": "Sign in to use your cart",
    "checkout.title": "Checkout", "checkout.address": "Delivery address", "checkout.addressHint": "Minimum 10 characters.", "checkout.payment": "Payment method", "checkout.vodafone": "Vodafone Cash", "checkout.instapay": "InstaPay", "checkout.screenshot": "Payment screenshot", "checkout.screenshotHint": "Required by the backend for order confirmation.", "checkout.place": "Confirm order", "checkout.processing": "Submitting order…", "checkout.notice": "Payment account details are intentionally not invented here; use the merchant details supplied by the store.", "checkout.success": "Order confirmed successfully.", "checkout.orderId": "Order ID",
    "admin.title": "VANTA Admin", "admin.dashboard": "Dashboard", "admin.products": "Products", "admin.orders": "Orders", "admin.users": "Users", "admin.categories": "Categories", "admin.access": "Admin access", "admin.unauthorized": "Admin access is required.", "admin.load": "Loading admin data…", "admin.errorTitle": "Admin section failed", "admin.errorDescription": "This section hit an unexpected error. Retry without losing the rest of the app.", "admin.metrics": "Overview", "admin.totalProducts": "Active products", "admin.totalOrders": "Orders", "admin.totalUsers": "Users", "admin.revenue": "Order value", "admin.add": "Add product", "admin.edit": "Edit", "admin.toggle": "Toggle active", "admin.delete": "Delete", "admin.status": "Status", "admin.search": "Search", "admin.save": "Save changes", "admin.cancel": "Cancel", "admin.noCategoryApi": "The backend exposes no category CRUD endpoints. Categories are derived from active products, so this screen is intentionally read-only.",
    "common.loading": "Loading…", "common.retry": "Retry", "common.close": "Close", "common.error": "Something went wrong.", "common.network": "Network error. Check your connection and API URL.", "common.required": "Required", "common.success": "Success",
    "error.title": "This page ran into a problem", "error.description": "The surrounding application remains available. Retry this route to continue.", "error.notFound": "That page does not exist.",
    "search.placeholder": "Search VANTA"
  },
  ar: {
    "nav.home": "الرئيسية", "nav.shop": "المتجر", "nav.orders": "الطلبات", "nav.admin": "الإدارة", "nav.search": "بحث", "nav.theme": "المظهر", "nav.language": "اللغة", "nav.cart": "السلة", "nav.account": "الحساب", "nav.login": "تسجيل الدخول", "nav.openMenu": "فتح القائمة", "nav.mobile": "التنقل على الهاتف", "nav.primary": "التنقل الرئيسي",
    "home.eyebrow": "فانتا / إصدار الخريف", "home.title": "ثقة هادئة. قطع تتلبس كل يوم.", "home.description": "خزانة عصرية من القطع الأساسية — قصّات نظيفة، خامات واضحة، وقطع معمولة عشان تعيش معاك.", "home.shop": "تسوق الإصدار", "home.discover": "اكتشف المجموعة", "home.categories": "تسوق حسب التصنيف", "home.featured": "قطع مختارة", "home.editorial": "الزي اليومي", "home.editorialBody": "اللبس الحلو يندمج مع يومك، وفي نفس الوقت يخلي الإطلالة كلها مقصودة.", "home.viewAll": "عرض الكل", "home.values": "ضوضاء أقل. قطع أفضل.", "home.valuesBody": "فانتا بتحافظ على لغة بصرية هادئة وتجربة منتجات دقيقة.", "home.cta": "كوّن اختياراتك",
    "shop.title": "المجموعة", "shop.description": "استكشف قطع فانتا الحالية وفلترها حسب ذوقك.", "shop.search": "ابحث باسم المنتج", "shop.category": "التصنيف", "shop.color": "اللون", "shop.size": "المقاس", "shop.minPrice": "أقل سعر", "shop.maxPrice": "أعلى سعر", "shop.sort": "ترتيب", "shop.newest": "الأحدث", "shop.priceLow": "السعر: من الأقل للأعلى", "shop.priceHigh": "السعر: من الأعلى للأقل", "shop.clear": "مسح الفلاتر", "shop.results": "نتيجة", "shop.empty": "مفيش قطع مطابقة للفلاتر دي.", "shop.filters": "الفلاتر",
    "product.size": "المقاس", "product.color": "اللون", "product.quantity": "الكمية", "product.add": "أضف للسلة", "product.selectSize": "اختار المقاس", "product.selectColor": "اختار اللون", "product.out": "نفد المخزون", "product.lowStock": "الكمية قليلة", "product.description": "الوصف", "product.shipping": "تفاصيل التوصيل", "product.shippingBody": "التوصيل بيتم عن طريق المتجر. إجمالي الطلب المعروض هنا جاي من الباك إند مباشرة.", "product.related": "ممكن يعجبك كمان", "product.back": "العودة للمتجر",
    "auth.login": "تسجيل الدخول", "auth.signup": "إنشاء حساب", "auth.email": "البريد الإلكتروني", "auth.password": "كلمة المرور", "auth.name": "الاسم بالكامل", "auth.phone": "رقم الهاتف", "auth.otp": "كود التحقق", "auth.sendOtp": "إرسال كود التحقق", "auth.otpSent": "الكود اتبعت. راجع بريدك.", "auth.noAccount": "لسه جديد على فانتا؟", "auth.haveAccount": "عندك حساب بالفعل؟", "auth.create": "إنشاء حساب", "auth.signing": "جاري التنفيذ…", "auth.passwordHint": "6 حروف على الأقل", "auth.otpHint": "6 أرقام", "auth.loginSuccess": "نورت تاني.", "auth.signupSuccess": "الحساب اتعمل. تقدر تسجل دخول.",
    "account.title": "حسابك", "account.profile": "البيانات", "account.name": "الاسم", "account.email": "البريد", "account.phone": "الهاتف", "account.orders": "طلباتك", "account.cart": "سلتك", "account.logout": "تسجيل الخروج", "account.loggedOut": "أنت مش مسجل دخول.", "account.login": "اذهب لتسجيل الدخول",
    "orders.title": "طلباتك", "orders.empty": "لسه مفيش طلبات.", "orders.order": "الطلب", "orders.status": "الحالة", "orders.total": "الإجمالي", "orders.date": "التاريخ", "orders.items": "منتجات", "orders.view": "عرض المنتجات", "orders.unauthorized": "سجل الدخول عشان تشوف طلباتك.",
    "cart.title": "السلة", "cart.empty": "السلة فاضية.", "cart.browse": "تصفح المجموعة", "cart.subtotal": "الإجمالي الفرعي", "cart.checkout": "المتابعة للدفع", "cart.remove": "حذف", "cart.unavailable": "غير متاح", "cart.refresh": "تحديث السلة", "cart.signin": "سجل الدخول عشان تستخدم السلة",
    "checkout.title": "إتمام الطلب", "checkout.address": "عنوان التوصيل", "checkout.addressHint": "10 حروف على الأقل.", "checkout.payment": "طريقة الدفع", "checkout.vodafone": "فودافون كاش", "checkout.instapay": "إنستا باي", "checkout.screenshot": "صورة الدفع", "checkout.screenshotHint": "مطلوبة من الباك إند لتأكيد الطلب.", "checkout.place": "تأكيد الطلب", "checkout.processing": "جاري إرسال الطلب…", "checkout.notice": "بيانات حساب الدفع مش هنخترعها؛ استخدم بيانات التاجر اللي بيوفرها المتجر.", "checkout.success": "تم تأكيد الطلب بنجاح.", "checkout.orderId": "رقم الطلب",
    "admin.title": "إدارة فانتا", "admin.dashboard": "لوحة التحكم", "admin.products": "المنتجات", "admin.orders": "الطلبات", "admin.users": "المستخدمون", "admin.categories": "التصنيفات", "admin.access": "صلاحية الإدارة", "admin.unauthorized": "صلاحية الإدارة مطلوبة.", "admin.load": "جاري تحميل بيانات الإدارة…", "admin.errorTitle": "حصلت مشكلة في قسم الإدارة", "admin.errorDescription": "القسم واجه خطأ غير متوقع. جرّب مرة تانية من غير ما باقي التطبيق يتأثر.", "admin.metrics": "نظرة عامة", "admin.totalProducts": "المنتجات المتاحة", "admin.totalOrders": "الطلبات", "admin.totalUsers": "المستخدمون", "admin.revenue": "قيمة الطلبات", "admin.add": "إضافة منتج", "admin.edit": "تعديل", "admin.toggle": "تغيير الحالة", "admin.delete": "حذف", "admin.status": "الحالة", "admin.search": "بحث", "admin.save": "حفظ التعديلات", "admin.cancel": "إلغاء", "admin.noCategoryApi": "الباك إند مش موفر endpoints لإضافة/تعديل/حذف التصنيفات. التصنيفات هنا مستخرجة من المنتجات المتاحة، لذلك الصفحة للعرض فقط.",
    "common.loading": "جاري التحميل…", "common.retry": "حاول مرة أخرى", "common.close": "إغلاق", "common.error": "حصلت مشكلة.", "common.network": "مشكلة في الشبكة. راجع الاتصال ورابط الـ API.", "common.required": "مطلوب", "common.success": "تم بنجاح",
    "error.title": "الصفحة واجهت مشكلة", "error.description": "باقي التطبيق شغال. جرّب المسار ده مرة تانية.", "error.notFound": "الصفحة دي مش موجودة.",
    "search.placeholder": "ابحث في فانتا"
  }
};

export function getServerDictionary(locale: Locale) {
  return DICTIONARY[locale];
}
